version: '3.9'
services:
  db:
    image: postgres:16
    container_name: user_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: docutrace_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    container_name: user_service
    depends_on:
      - db
    env_file:
      - ./user-service/.env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "70:8080"
    # Healthcheck could be added for readiness

volumes:
  pgdata:
