name: Frontend CI/CD

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop, feature/*]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/docutrace-frontend:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docutrace-frontend:${IMAGE_TAG}

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.9.0

      - name: Update image tag in k8s manifests
        run: |
          sed -i "s|image: .*/docutrace-frontend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/docutrace-frontend:${IMAGE_TAG}|g" frontend/k8s/deployment.yaml

      - name: Deploy to Kind
        run: |
          kubectl apply -f frontend/k8s/

      - name: Wait for frontend pod to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app=frontend -n default --timeout=120s || {
            echo 'Pod did not become ready. Printing pod status and logs:';
            kubectl get pods -l app=frontend -n default;
            kubectl describe pod -l app=frontend -n default;
            kubectl logs $(kubectl get pods -l app=frontend -n default -o jsonpath='{.items[0].metadata.name}');
            exit 1;
          }

      - name: Port-forward frontend
        run: |
          kubectl port-forward svc/frontend 8080:80 &
          sleep 10

      - name: Check frontend HTTP response
        run: |
          curl -f http://127.0.0.1:8080 || (echo 'Frontend not responding' && exit 1)

      - name: Show frontend pod logs on failure
        if: failure()
        run: |
          echo '--- frontend pod logs (failure) ---'
          kubectl logs $(kubectl get pods -l app=frontend -n default -o jsonpath='{.items[0].metadata.name}') -n default || echo 'Could not get logs.'
